- name: Deploy HTML with Jinja2 template
  hosts: all
  become: true

  tasks:
    - name: Ensure /var/www/html exists
      file:
        path: /var/www/html
        state: directory

    - name: Deploy index.html from template
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
