- name: Pull vote image
  docker_image:
    name: dockersamples/examplevotingapp_vote
    source: pull

- name: Run vote container
  docker_container:
    name: vote
    image: dockersamples/examplevotingapp_vote
    ports:
      - "5000:80"
    env:
      REDIS_HOST: 127.0.0.1
