---
- name: Deploy vote microservice
  hosts: frontend
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker if not present
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Create microservices network (if not exists)
      docker_network:
        name: microservices
        state: present

    - name: Pull Docker image for vote
      docker_image:
        name: pokfinner/vote
        source: pull
        tag: latest

    - name: Run vote container
      docker_container:
        name: vote
        image: pokfinner/vote:latest
        env:
          REDIS_HOST: 10.0.2.207
        ports:
          - "80:80"
        state: started
        networks:
          - name: microservices

    - name: Pull Docker image for result
      docker_image:
        name: pokfinner/result
        source: pull
        tag: latest

    - name: Run result container
      docker_container:
        name: result
        image: pokfinner/result:latest
        env:
          PG_HOST: 10.0.3.182
          PG_PORT: "5432"
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: postgres
        ports:
          - "81:80"
        state: started
        networks:
          - name: microservices
