---
- name: redis
  hosts: redis
  become: yes
  roles:
    - redis

- name: vote
  hosts: vote
  become: yes
  roles:
    - vote

- name: result
  hosts: result
  become: yes
  roles:
    - result

- name: worker
  hosts: worker
  become: yes
  roles:
    - worker

- name: nginx
  hosts: nginx
  become: yes
  roles:
    - nginx
